### ISSUE TITLE
fix: Incompatible libraries

### ISSUE THREAD

**Issue by omibo** [drcapybara/capyCRYPT#58]
When updating the libraries using `cargo update`, Capycrypt is not compatible with Tiny_ed448_goldilocks, resulting in a compile-time error.

**Comment by omibo** [comment]
In the newer version of Tiny_ed448_goldilocks, the functions Scalar.mul_mod_r() and ExtendedPoint::tw_generator() are not defined.

**Comment by drcapybara** [comment]
thanks for pointing this out. some functions were renamed on the curve library during the last published version. Ive gone ahead and pushed up a fix for this.
